#!/usr/local/bin/dill read
# Fake example file
[meta]
format = "Dill" # Case insensitive. For non-standard extensions: only change if you make incompatible changes
version.toml = "0.5.0"
version.dill = "1"
document.language = "eng" # ISO 639-3 code if available, if not then just the name of the language

[define] # For defining how tbc should display non-standard custom.* keys, if not defined here then dill will use custom."whatever is here"
defined = "A defined custom thing" # Will define custom.defined, do not put the custom.* prefix here

[data]
name.first = "Basil"
name.middle = "Placeholder"
name.last = "Chinchilla"
birthdate = 2010-08-16
extension.someidcode.numeric = "44300236" # Non standard extension, dill will not display it
extension.someidcode.alphanumeric = "9A233HVTM529"
custom."Some custom thing" = "Hello" # Other type of non-standard extension, cannot be nested
custom.defined = "Cats are not dogs" # Same as above, defined in define
location.pluscode.Home = "9GWF38F8+F4" # For everything ending in .Home or .Work, .Home/.Work can be replaced by any string
location.latlong.Home = [68.073688, 29.315312] # First latitide, then longitude
location.address.Home = "Korvantunturi, Lapland, Finland"
location.postcode.Home = "99999"
contact.phone.Home = "+442079460700"
contact.email.Home = "basil-home@mail.example.org"
location.address.Work = "Helsinki, Finland"
contact.email.Work = "basil-work@workmail.example.org"
contact.username.GitHub = "@example-basil-home" # Can be contact.username."Anything that you want dill to display"
contact.username.Twitter = "@example-basil-home"
organization = "None"
citizenship = ["Finland", "UK"]
website = "https://basil.example.org/"
description = "Hello, I live in Finland but have a UK phone number!"
languages.fluent = ["eng", "rus", "fin"] # ISO 639-3 Codes if available, if not then the name of the language
job = "Not being a cat"
gender = "Unknown" # Can be whatever you want dill to display